In [1]:
import tushare as ts
import json
import pandas as pd

results = pd.DataFrame()

In [5]:
data = pd.read_excel('/Users/chenoi/Desktop/总.xlsx')
data

           证券代码    证券简称  一级行业      二级行业      三级行业
0     000001.SZ    平安银行    银行       银行Ⅱ       银行Ⅲ
1     000002.SZ     万科A   房地产    房地产开发Ⅱ    房地产开发Ⅲ
2     000004.SZ    国华网安   计算机     计算机应用      IT服务
3     000005.SZ    ST星源  公用事业  环保工程及服务Ⅱ  环保工程及服务Ⅲ
4     000006.SZ    深振业A   房地产    房地产开发Ⅱ    房地产开发Ⅲ
...         ...     ...   ...       ...       ...
4781  900945.SH  *ST海航B  交通运输     航空运输Ⅱ     航空运输Ⅲ
4782  900946.SH    天雁B股    汽车    汽车零部件Ⅱ    汽车零部件Ⅲ
4783  900947.SH    振华B股  机械设备      专用设备      重型机械
4784  900952.SH    锦港B股  交通运输       港口Ⅱ       港口Ⅲ
4785  900955.SH  *ST海创B  休闲服务     旅游综合Ⅱ     旅游综合Ⅲ

[4786 rows x 5 columns]

In [8]:
list1 = []
list1.append(data.loc[data["证券代码"] == '900955.SH', "一级行业"].iloc[0])

In [9]:
list1

['休闲服务']

In [2]:
with open('/Users/chenoi/Desktop/stock_codes.json','r') as f:
    data = json.load(f)
    
stock_list = data.split(",")
pro = ts.pro_api()

In [4]:
ts.set_token("25dbbe173567b0dc611ad5278f902aa6c7267b5db1941d767072ccfa")
pro = ts.pro_api()
df = pro.index_member(ts_code='000001.SZ')

Exception: 抱歉，您没有访问该接口的权限，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

In [3]:
data = pro.stock_basic(exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
data

        ts_code  symbol     name  area industry list_date
0     000001.SZ  000001     平安银行    深圳       银行  19910403
1     000002.SZ  000002      万科A    深圳     全国地产  19910129
2     000004.SZ  000004     国华网安    深圳     软件服务  19910114
3     000005.SZ  000005     ST星源    深圳     环境保护  19901210
4     000006.SZ  000006     深振业A    深圳     区域地产  19920427
...         ...     ...      ...   ...      ...       ...
4690  871553.BJ  871553     凯腾精工  None     None  20210806
4691  871642.BJ  871642     通易航天  None     None  20210816
4692  871981.BJ  871981     晶赛科技  None     None  20211115
4693  872925.BJ  872925     锦好医疗  None     None  20211025
4694  689009.SH  689009  九号公司-WD    北京      摩托车  20201029

[4695 rows x 6 columns]

In [4]:
# 返回所有相关的股票列
data = data[data['ts_code'].isin(stock_list)]

In [5]:
list1 = []
list2 = []
for i in range(0, len(stock_list)):
    try:
        list1.append(data.loc[data['ts_code'] == stock_list[i], 'name'].iloc[0])
#         list2.append(data.loc[data['industry'] == stock_list[i], 'name'].iloc[0])
    except IndexError:
        list1.append("不上市了")
#         list2.append("不上市了")
results["code"] = pd.DataFrame(stock_list)

In [6]:
results["name"] = pd.DataFrame(list1)

In [7]:
# results["industry"] = pd.DataFrame(list2)

In [8]:
results

          code  name
0    600256.SH  广汇能源
1    600339.SH  中油工程
2    600348.SH  华阳股份
3    600387.SH  ST海越
4    600395.SH  盘江股份
..         ...   ...
290  000671.SZ   阳光城
291  000718.SZ  苏宁环球
292  000720.SZ  新能泰山
293  000732.SZ  泰禾集团
294  000736.SZ  中交地产

[295 rows x 2 columns]

In [9]:
results = results[~results["name"].isin(["不上市了"])]

In [10]:
results

          code  name
0    600256.SH  广汇能源
1    600339.SH  中油工程
2    600348.SH  华阳股份
3    600387.SH  ST海越
4    600395.SH  盘江股份
..         ...   ...
290  000671.SZ   阳光城
291  000718.SZ  苏宁环球
292  000720.SZ  新能泰山
293  000732.SZ  泰禾集团
294  000736.SZ  中交地产

[294 rows x 2 columns]

In [11]:
def whatdowebuy(stock_list):
    results = pd.DataFrame()
    data = pro.stock_basic(exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
    # 返回所有相关的股票列
    data = data[data['ts_code'].isin(stock_list)]
    list1 = []
    for i in range(0, len(stock_list)):
        try:
            list1.append(data.loc[data['ts_code'] == stock_list[i], 'name'].iloc[0])
        #         list2.append(data.loc[data['industry'] == stock_list[i], 'name'].iloc[0])
        except IndexError:
            list1.append("不上市了")
    #         list2.append("不上市了")
    results["code"] = pd.DataFrame(stock_list)
    results["name"] = pd.DataFrame(list1)
    results = results[~results["name"].isin(["不上市了"])]
    return results["name"]

In [12]:
file = open("/Users/chenoi/Desktop/the_truth.txt", 'r')
js = file.read()
dict1 = json.loads(js)
sums = list(dict1.values())
keys = list(dict1.keys())
sums

[['000069.SZ',
  '000016.SZ',
  '000156.SZ',
  '000507.SZ',
  '000498.SZ',
  '000429.SZ',
  '000516.SZ',
  '000518.SZ',
  '000089.SZ',
  '000425.SZ',
  '000400.SZ',
  '000417.SZ',
  '000338.SZ',
  '000504.SZ',
  '000157.SZ',
  '000501.SZ',
  '000538.SZ',
  '000521.SZ',
  '000099.SZ',
  '000524.SZ',
  '000333.SZ',
  '000705.SZ',
  '000553.SZ',
  '000525.SZ',
  '000790.SZ',
  '000710.SZ',
  '000716.SZ',
  '600968.SH',
  '600792.SH',
  '000729.SZ',
  '600740.SH',
  '000759.SZ',
  '600688.SH',
  '000799.SZ',
  '600985.SH',
  '600583.SH',
  '000858.SZ',
  '600508.SH',
  '000860.SZ',
  '000958.SZ',
  '600408.SH',
  '600403.SH',
  '600395.SH',
  '600348.SH',
  '000876.SZ',
  '600339.SH',
  '600546.SH',
  '000639.SZ',
  '000813.SZ',
  '600997.SH',
  '000523.SZ',
  '000568.SZ',
  '000488.SZ',
  '000422.SZ',
  '000028.SZ',
  '000301.SZ',
  '000576.SZ',
  '000739.SZ',
  '000895.SZ',
  '000012.SZ',
  '000060.SZ',
  '601088.SH',
  '000756.SZ',
  '000596.SZ',
  '601015.SH',
  '601011.SH',
  '000030.SZ'],
 ['000759.SZ',
  '002467.SZ',
  '000860.SZ',
  '000596.SZ',
  '000061.SZ',
  '000524.SZ',
  '000555.SZ',
  '000581.SZ',
  '000526.SZ',
  '000070.SZ',
  '000810.SZ',
  '000587.SZ',
  '000158.SZ',
  '000576.SZ',
  '000100.SZ',
  '000333.SZ',
  '000725.SZ',
  '000156.SZ',
  '000543.SZ',
  '300578.SZ',
  '000899.SZ',
  '000488.SZ',
  '000401.SZ',
  '000002.SZ',
  '000060.SZ',
  '000012.SZ',
  '601015.SH',
  '000517.SZ',
  '600997.SH',
  '600985.SH',
  '000546.SZ',
  '000560.SZ',
  '600740.SH',
  '000615.SZ',
  '600688.SH',
  '600583.SH',
  '000656.SZ',
  '600508.SH',
  '000671.SZ',
  '600408.SH',
  '000732.SZ',
  '600339.SH',
  '000573.SZ',
  '000883.SZ',
  '000553.SZ',
  '000875.SZ',
  '000016.SZ',
  '000507.SZ',
  '000498.SZ',
  '000400.SZ',
  '000027.SZ',
  '000338.SZ',
  '000157.SZ',
  '000155.SZ',
  '000539.SZ',
  '000099.SZ',
  '000090.SZ',
  '000039.SZ',
  '000591.SZ',
  '000009.SZ',
  '000600.SZ',
  '000008.SZ',
  '000672.SZ',
  '000655.SZ',
  '000722.SZ',
  '000630.SZ',
  '000767.SZ',
  '000612.SZ',
  '000603.SZ',
  '000030.SZ',
  '000869.SZ',
  '000987.SZ',
  '000739.SZ',
  '000513.SZ',
  '000813.SZ',
  '000066.SZ',
  '002608.SZ',
  '000538.SZ',
  '000062.SZ',
  '000050.SZ',
  '000661.SZ',
  '000063.SZ',
  '000021.SZ',
  '000650.SZ',
  '000423.SZ',
  '000876.SZ',
  '000034.SZ'],
 ['000060.SZ',
  '000810.SZ',
  '000012.SZ',
  '000090.SZ',
  '000899.SZ',
  '000488.SZ',
  '000576.SZ',
  '600583.SH',
  '000021.SZ',
  '000513.SZ',
  '000543.SZ',
  '000538.SZ',
  '000555.SZ',
  '000560.SZ',
  '000573.SZ',
  '000526.SZ',
  '000739.SZ',
  '000656.SZ',
  '000596.SZ',
  '000546.SZ',
  '000016.SZ',
  '000002.SZ',
  '000099.SZ',
  '000301.SZ',
  '000725.SZ',
  '000813.SZ',
  '000401.SZ',
  '000400.SZ',
  '000027.SZ',
  '000498.SZ',
  '000063.SZ',
  '000581.SZ',
  '000524.SZ',
  '000338.SZ',
  '000050.SZ',
  '000539.SZ',
  '000966.SZ',
  '000157.SZ',
  '000423.SZ',
  '600740.SH',
  '000587.SZ',
  '000039.SZ',
  '600688.SH',
  '000061.SZ',
  '002467.SZ',
  '002608.SZ',
  '000507.SZ',
  '000615.SZ',
  '000155.SZ',
  '000422.SZ',
  '000722.SZ',
  '000070.SZ',
  '000062.SZ',
  '000009.SZ',
  '000799.SZ',
  '000732.SZ',
  '000767.SZ',
  '000600.SZ',
  '000517.SZ',
  '000671.SZ',
  '000875.SZ',
  '000030.SZ',
  '000156.SZ',
  '000100.SZ',
  '000650.SZ',
  '600997.SH',
  '000672.SZ',
  '000008.SZ',
  '000661.SZ',
  '000612.SZ',
  '601015.SH',
  '000603.SZ',
  '600985.SH',
  '000591.SZ',
  '000860.SZ',
  '300578.SZ',
  '000876.SZ',
  '000883.SZ',
  '600339.SH',
  '000034.SZ',
  '000333.SZ',
  '000987.SZ',
  '000066.SZ',
  '000869.SZ',
  '000553.SZ',
  '000759.SZ',
  '600508.SH'],
 ['000060.SZ',
  '000498.SZ',
  '000156.SZ',
  '000021.SZ',
  '000401.SZ',
  '000063.SZ',
  '000027.SZ',
  '000517.SZ',
  '600339.SH',
  '000860.SZ',
  '000301.SZ',
  '000987.SZ',
  '000546.SZ',
  '000155.SZ',
  '000157.SZ',
  '000016.SZ',
  '000739.SZ',
  '000596.SZ',
  '000591.SZ',
  '000543.SZ',
  '000813.SZ',
  '000090.SZ',
  '000034.SZ',
  '000099.SZ',
  '000875.SZ',
  '000526.SZ',
  '000661.SZ',
  '000587.SZ',
  '000012.SZ',
  '002608.SZ',
  '000061.SZ',
  '000100.SZ'],
 ['000031.SZ',
  '002467.SZ',
  '000012.SZ',
  '000016.SZ',
  '000513.SZ',
  '601015.SH',
  '000030.SZ',
  '300578.SZ',
  '600050.SH',
  '300921.SZ',
  '000507.SZ',
  '000498.SZ',
  '000060.SZ',
  '601011.SH',
  '000517.SZ',
  '000739.SZ',
  '000869.SZ',
  '000425.SZ',
  '000035.SZ',
  '000883.SZ',
  '000591.SZ',
  '000546.SZ',
  '000032.SZ',
  '000661.SZ',
  '000593.SZ',
  '000553.SZ',
  '000009.SZ',
  '000875.SZ',
  '000045.SZ',
  '000600.SZ',
  '000008.SZ',
  '000650.SZ',
  '000601.SZ',
  '000672.SZ',
  '000605.SZ',
  '000603.SZ',
  '000669.SZ',
  '000612.SZ',
  '000655.SZ',
  '000034.SZ',
  '000722.SZ',
  '000544.SZ',
  '600804.SH',
  '000039.SZ',
  '000049.SZ',
  '603171.SH',
  '000002.SZ',
  '000400.SZ',
  '000301.SZ',
  '000021.SZ',
  '000338.SZ',
  '000027.SZ',
  '000401.SZ',
  '000050.SZ',
  '000966.SZ',
  '000157.SZ',
  '000518.SZ',
  '000155.SZ',
  '000422.SZ',
  '000099.SZ',
  '000539.SZ',
  '000538.SZ',
  '000899.SZ',
  '000090.SZ',
  '000488.SZ',
  '000543.SZ',
  '000710.SZ',
  '000065.SZ',
  '000525.SZ',
  '000062.SZ',
  '000026.SZ',
  '000630.SZ',
  '000541.SZ',
  '000876.SZ',
  '000716.SZ',
  '000725.SZ',
  '600740.SH',
  '600508.SH',
  '000573.SZ',
  '000727.SZ',
  '000158.SZ',
  '000066.SZ',
  '000526.SZ',
  '000733.SZ',
  '600408.SH',
  '000524.SZ',
  '000423.SZ',
  '000799.SZ',
  '000671.SZ',
  '000656.SZ',
  '000521.SZ',
  '000564.SZ',
  '000581.SZ',
  '000403.SZ',
  '600583.SH',
  '000606.SZ',
  '000028.SZ',
  '000568.SZ',
  '000061.SZ',
  '000895.SZ',
  '000555.SZ',
  '000048.SZ',
  '000576.SZ',
  '000636.SZ',
  '000615.SZ',
  '600546.SH',
  '000063.SZ',
  '002608.SZ',
  '600688.SH',
  '000813.SZ',
  '000596.SZ',
  '000100.SZ',
  '000759.SZ',
  '000523.SZ',
  '000333.SZ',
  '000501.SZ',
  '000858.SZ',
  '600395.SH',
  '600339.SH',
  '000756.SZ',
  '000504.SZ',
  '000417.SZ',
  '000823.SZ',
  '000156.SZ',
  '600997.SH',
  '000848.SZ',
  '600968.SH',
  '000987.SZ',
  '600985.SH',
  '600403.SH',
  '000810.SZ',
  '000958.SZ',
  '000070.SZ',
  '000560.SZ',
  '000069.SZ',
  '000732.SZ'],
 ['000732.SZ',
  '000813.SZ',
  '000858.SZ',
  '600339.SH',
  '000655.SZ',
  '000525.SZ',
  '000049.SZ',
  '000899.SZ',
  '000722.SZ',
  '000612.SZ',
  '000895.SZ',
  '000090.SZ',
  '000576.SZ',
  '000034.SZ',
  '000070.SZ',
  '000488.SZ',
  '000543.SZ',
  '600546.SH',
  '000568.SZ',
  '000555.SZ',
  '000630.SZ',
  '000538.SZ',
  '000065.SZ',
  '000869.SZ',
  '000008.SZ',
  '000596.SZ',
  '000523.SZ',
  '000593.SZ',
  '000759.SZ',
  '000009.SZ',
  '000066.SZ',
  '000553.SZ',
  '000601.SZ',
  '000045.SZ',
  '000875.SZ',
  '600403.SH',
  '000799.SZ',
  '000671.SZ',
  '000600.SZ',
  '000100.SZ',
  '000650.SZ',
  '600408.SH',
  '000032.SZ',
  '000661.SZ',
  '000603.SZ',
  '000544.SZ',
  '000656.SZ',
  '000605.SZ',
  '000035.SZ',
  '000987.SZ',
  '000883.SZ',
  '000716.SZ',
  '600508.SH',
  '000672.SZ',
  '600395.SH',
  '000848.SZ',
  '000158.SZ',
  '000591.SZ',
  '000546.SZ',
  '000039.SZ',
  '000876.SZ',
  '000517.SZ',
  '000425.SZ',
  '000501.SZ',
  '600050.SH',
  '000513.SZ',
  '000521.SZ',
  '000012.SZ',
  '000498.SZ',
  '000423.SZ',
  '000710.SZ',
  '000524.SZ',
  '000733.SZ',
  '600804.SH',
  '000958.SZ',
  '000028.SZ',
  '000526.SZ',
  '000060.SZ',
  '000002.SZ',
  '600740.SH',
  '000560.SZ',
  '000507.SZ',
  '000810.SZ',
  '000031.SZ',
  '002467.SZ',
  '000062.SZ',
  '000069.SZ',
  '600997.SH',
  '000156.SZ',
  '000026.SZ',
  '600985.SH',
  '601011.SH',
  '603171.SH',
  '000739.SZ',
  '000504.SZ',
  '000333.SZ',
  '300578.SZ',
  '601015.SH',
  '000756.SZ',
  '600968.SH',
  '300921.SZ',
  '000417.SZ',
  '000823.SZ',
  '000727.SZ',
  '000099.SZ',
  '000573.SZ',
  '000581.SZ',
  '600688.SH',
  '000966.SZ',
  '000063.SZ',
  '000615.SZ',
  '000636.SZ',
  '000518.SZ',
  '000589.SZ',
  '000027.SZ',
  '000048.SZ',
  '000401.SZ',
  '000021.SZ',
  '000061.SZ',
  '000422.SZ',
  '000030.SZ',
  '000606.SZ',
  '600583.SH',
  '000539.SZ',
  '000155.SZ',
  '000564.SZ',
  '000157.SZ',
  '002608.SZ',
  '000403.SZ',
  '000050.SZ',
  '000301.SZ',
  '000338.SZ',
  '000400.SZ',
  '000725.SZ',
  '000541.SZ'],
 ['600339.SH',
  '600408.SH',
  '000060.SZ',
  '000002.SZ',
  '000546.SZ',
  '000739.SZ',
  '000650.SZ',
  '000612.SZ',
  '002608.SZ',
  '000661.SZ',
  '000021.SZ',
  '600997.SH',
  '000517.SZ',
  '000732.SZ',
  '600583.SH',
  '000603.SZ',
  '600688.SH',
  '000883.SZ',
  '000553.SZ',
  '000671.SZ',
  '000560.SZ',
  '000966.SZ',
  '000012.SZ',
  '600403.SH',
  '000656.SZ',
  '000813.SZ',
  '000031.SZ',
  '600740.SH',
  '000615.SZ',
  '000756.SZ',
  '000301.SZ',
  '601015.SH',
  '000987.SZ',
  '000401.SZ',
  '000422.SZ',
  '600804.SH',
  '000016.SZ',
  '000155.SZ',
  '000526.SZ',
  '000099.SZ',
  '000539.SZ',
  '000725.SZ',
  '000581.SZ',
  '000090.SZ',
  '000538.SZ',
  '000063.SZ',
  '000543.SZ',
  '000061.SZ',
  '000555.SZ',
  '000039.SZ',
  '000035.SZ',
  '000876.SZ',
  '000157.SZ',
  '000596.SZ',
  '000423.SZ',
  '000027.SZ',
  '000498.SZ',
  '000513.SZ',
  '300921.SZ',
  '300578.SZ',
  '000425.SZ',
  '601728.SH',
  '002467.SZ',
  '000030.SZ',
  '603171.SH',
  '000062.SZ',
  '000400.SZ',
  '000050.SZ',
  '000156.SZ',
  '000333.SZ',
  '000338.SZ',
  '000810.SZ',
  '000591.SZ',
  '000636.SZ',
  '000507.SZ',
  '000799.SZ',
  '000858.SZ',
  '000066.SZ',
  '000600.SZ',
  '000008.SZ',
  '000100.SZ',
  '000070.SZ',
  '000655.SZ',
  '000672.SZ',
  '000045.SZ',
  '000630.SZ',
  '000034.SZ',
  '000848.SZ',
  '000716.SZ',
  '000722.SZ',
  '000009.SZ',
  '000032.SZ',
  '000158.SZ',
  '000869.SZ'],
 ['000848.SZ',
  '000066.SZ',
  '600985.SH',
  '000156.SZ',
  '600339.SH',
  '000062.SZ',
  '000858.SZ',
  '000031.SZ',
  '000732.SZ',
  '300578.SZ',
  '000517.SZ',
  '000030.SZ',
  '300921.SZ',
  '000869.SZ',
  '002467.SZ',
  '000739.SZ',
  '000026.SZ',
  '000509.SZ',
  '000860.SZ',
  '000016.SZ',
  '601015.SH',
  '000070.SZ',
  '600997.SH',
  '000596.SZ',
  '000810.SZ',
  '000158.SZ',
  '000876.SZ',
  '000576.SZ',
  '600546.SH',
  '000813.SZ',
  '000555.SZ',
  '000523.SZ',
  '000061.SZ',
  '600583.SH',
  '000063.SZ',
  '000615.SZ',
  '600408.SH',
  '000716.SZ',
  '000507.SZ',
  '000333.SZ',
  '000636.SZ',
  '000100.SZ',
  '000581.SZ',
  '000403.SZ',
  '000671.SZ',
  '000725.SZ',
  '000573.SZ',
  '000526.SZ',
  '002608.SZ',
  '600740.SH',
  '000524.SZ',
  '000799.SZ',
  '000656.SZ',
  '000987.SZ',
  '000423.SZ',
  '000759.SZ',
  '000560.SZ',
  '000722.SZ',
  '000498.SZ',
  '000301.SZ',
  '000600.SZ',
  '000008.SZ',
  '000875.SZ',
  '000027.SZ',
  '000966.SZ',
  '000553.SZ',
  '000157.SZ',
  '000155.SZ',
  '000009.SZ',
  '000401.SZ',
  '000546.SZ',
  '000099.SZ',
  '000422.SZ',
  '000591.SZ',
  '000045.SZ',
  '000032.SZ',
  '000021.SZ',
  '000090.SZ',
  '000035.SZ',
  '000538.SZ',
  '000488.SZ',
  '000661.SZ',
  '000543.SZ',
  '000525.SZ',
  '000050.SZ',
  '000400.SZ',
  '000338.SZ',
  '000039.SZ',
  '000603.SZ',
  '000513.SZ',
  '000655.SZ',
  '000060.SZ',
  '000002.SZ',
  '601728.SH',
  '000630.SZ',
  '000650.SZ',
  '603171.SH',
  '000425.SZ',
  '000034.SZ',
  '000612.SZ',
  '000672.SZ',
  '000012.SZ'],
 ['000596.SZ',
  '000869.SZ',
  '000630.SZ',
  '000876.SZ',
  '000576.SZ',
  '000045.SZ',
  '000591.SZ',
  '000732.SZ',
  '600546.SH',
  '000860.SZ',
  '000661.SZ',
  '000555.SZ',
  '000612.SZ',
  '000032.SZ',
  '000656.SZ',
  '000799.SZ',
  '000066.SZ',
  '000672.SZ',
  '000034.SZ',
  '000600.SZ',
  '000987.SZ',
  '000848.SZ',
  '000671.SZ',
  '000875.SZ',
  '000061.SZ',
  '000655.SZ',
  '000100.SZ',
  '000759.SZ',
  '000813.SZ',
  '000553.SZ',
  '600339.SH',
  '000716.SZ',
  '000603.SZ',
  '000008.SZ',
  '000650.SZ',
  '000009.SZ',
  '000858.SZ',
  '000158.SZ',
  '000070.SZ',
  '000546.SZ',
  '000636.SZ',
  '600583.SH',
  '600985.SH',
  '000739.SZ',
  '000338.SZ',
  '000030.SZ',
  '000400.SZ',
  '600997.SH',
  '000517.SZ',
  '603171.SH',
  '601728.SH',
  '002467.SZ',
  '000002.SZ',
  '000026.SZ',
  '000301.SZ',
  '000060.SZ',
  '000050.SZ',
  '000722.SZ',
  '000509.SZ',
  '000425.SZ',
  '000513.SZ',
  '601015.SH',
  '300578.SZ',
  '601101.SH',
  '000012.SZ',
  '000031.SZ',
  '300921.SZ',
  '000507.SZ',
  '000016.SZ',
  '000823.SZ',
  '000156.SZ',
  '000062.SZ',
  '000063.SZ',
  '000488.SZ',
  '000615.SZ',
  '000538.SZ',
  '000021.SZ',
  '000498.SZ',
  '000581.SZ',
  '000899.SZ',
  '000564.SZ',
  '000090.SZ',
  '000422.SZ',
  '000725.SZ',
  '000573.SZ',
  '000403.SZ',
  '000526.SZ',
  '000099.SZ',
  '000155.SZ',
  '000524.SZ',
  '600740.SH',
  '002608.SZ',
  '000560.SZ',
  '000157.SZ',
  '000027.SZ',
  '000966.SZ',
  '000810.SZ',
  '000423.SZ',
  '000333.SZ',
  '000039.SZ',
  '000543.SZ']]

In [13]:

list3 = []
for i in range(0, len(sums)):
    list3.append(keys[i])
    list3.append(whatdowebuy(sums[i]))
resultss = pd.DataFrame(list3)
resultss

                                                    0
0                                            20210331
1   0     华侨城A
1     深康佳A
2     华数传媒
3      珠海港
4 ...
2                                            20210430
3   0     中百集团
1      二六三
2     顺鑫农业
3     古井贡酒
4 ...
4                                            20210531
5   0     中金岭南
1     创维数字
2      南玻A
3     天健集团
4 ...
6                                            20210630
7   0      中金岭南
1      山东路桥
2      华数传媒
3       深科...
8                                            20210731
9   0       大悦城
1       二六三
2       南玻A
3      深康佳...
10                                           20210831
11  0      泰禾集团
1      德展健康
2       五粮液
3      中油工...
12                                           20210930
13  0     中油工程
1     ST安泰
2     中金岭南
3      万科A
4 ...
14                                           20211031
15  0      承德露露
1      中国长城
2      淮北矿业
3      华数传...
16                                           20211130
17  0      古井贡酒
1       张裕A
2      铜陵有色
3       新希...

In [14]:
data.loc[data['ts_code'] == '000061.SZ', 'name'].iloc[0]

'农产品'

In [17]:
alwayswin = []
always = list(set.intersection(*map(set, sums)))
print(always)
for i in range(0, len(always)):
    alwayswin.append(data.loc[data['ts_code'] == always[i], 'name'].iloc[0])
    
print("该区间必选股票为： ")
print(alwayswin)

['000099.SZ', '000156.SZ', '000596.SZ', '000060.SZ', '000498.SZ', '000012.SZ', '000157.SZ', '600339.SH', '000813.SZ', '000739.SZ']
该区间必选股票为：
['中信海直', '华数传媒', '古井贡酒', '中金岭南', '山东路桥', '南玻A', '中联重科', '中油工程', '德展健康', '普洛药业']

In [16]:
newlist = [j for i in sums for j in i]
occurrences = Counter(newlist)
with open("/Users/"+user+"/Desktop/the_truth.txt", 'w') as fout:
    json_dumps_str = json.dumps(dict(occurrences), indent=4)
    print(json_dumps_str, file=fout)

NameError: name 'Counter' is not defined

In [ ]:
print(list(occurrences))

In [1]:
import pandas as pd

In [14]:
test = pd.read_excel("/Users/chenoi/Desktop/results.xlsx")

In [15]:
test

,Unnamed: 0,stock_names,date,risk_maxdownside2,avgreturny,pe_ttm,dividendyield,ps_ttm,pb_lf,peg,...,qfa_net_invest_inc_thiss,qfa_net_cash_flows_inv_act_thiss,qfa_oper_rev_lastseason,qfa_non_oper_rev_lastseason,qfa_net_profit_is_lastseason,qfa_net_invest_inc_lastseason,qfa_net_cash_flows_inv_act_lastseason,下个月平均收益,252日超额收益标准差,30/120日回报方差
0,0,600028.SH,20200131,-7.835821,-32.777054,12.892688,6.275304,0.195998,0.823939,0.031839,...,6.153000e+09,-49711000000,7.343090e+11,3.660000e+08,1.550800e+10,3.701000e+09,-2.167900e+10,-6.882591,0.000075,NaN
1,1,600121.SH,20200131,-12.549020,-53.752389,-35.345955,NaN,0.667798,0.792767,-0.129478,...,1.101461e+05,-141681708.93,9.314710e+08,1.980498e+07,-2.736802e+07,5.220896e+05,4.265801e+05,-9.417040,0.000173,NaN
2,2,600123.SH,20200131,-7.305936,-53.390434,8.360950,3.284072,0.830685,0.647172,-0.477914,...,3.161761e+07,-189506154.15,2.038584e+09,5.887012e+05,1.676976e+08,5.814378e+07,-1.195677e+08,-8.538588,0.000098,NaN
3,3,600188.SH,20200131,-10.536044,-65.538644,5.064477,16.322314,0.244554,0.771915,-0.263712,...,3.837010e+08,-2717590000,4.463548e+10,1.069390e+08,1.949192e+09,2.553090e+08,-1.233009e+09,-8.367769,0.000135,NaN
4,4,600256.SH,20200131,-6.609195,-18.378300,14.002833,NaN,1.642311,1.417896,-0.607578,...,-2.182170e+07,-791186196.31,3.414538e+09,1.831329e+06,3.833157e+08,-4.553727e+06,-9.667200e+08,-12.615385,0.000122,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15641,15641,300841.SZ,20220131,-11.109832,16823.526670,NaN,NaN,NaN,NaN,NaN,...,NaN,,2.282476e+08,4.186000e+05,3.311912e+08,1.245629e+06,-1.307398e+08,NaN,0.000286,
15642,15642,600079.SH,20220131,-4.746450,364.173743,NaN,NaN,NaN,NaN,NaN,...,NaN,,5.191756e+09,4.077402e+06,5.230038e+08,1.341188e+08,-2.772996e+08,NaN,0.000251,
15643,15643,600196.SH,20220131,-3.126277,53.395805,NaN,NaN,NaN,NaN,NaN,...,NaN,,1.009588e+10,2.163569e+06,1.181360e+09,6.783370e+08,-1.356588e+08,NaN,0.000325,
15644,15644,600267.SH,20220131,-3.994394,8438.293288,NaN,NaN,NaN,NaN,NaN,...,NaN,,3.103209e+09,1.148127e+07,2.174721e+08,1.516685e+08,-3.987874e+07,NaN,0.000203,
15645,15645,600276.SH,20220131,-9.213615,-81.047660,NaN,NaN,NaN,NaN,NaN,...,NaN,,6.901426e+09,1.487588e+06,1.529501e+09,6.593518e+07,-2.887987e+08,NaN,0.000197,

In [16]:
test.fillna('', inplace=True)

In [17]:
test.iloc[:, 2:200]

,date,risk_maxdownside2,avgreturny,pe_ttm,dividendyield,ps_ttm,pb_lf,peg,ev3,oper_rev,...,qfa_net_invest_inc_thiss,qfa_net_cash_flows_inv_act_thiss,qfa_oper_rev_lastseason,qfa_non_oper_rev_lastseason,qfa_net_profit_is_lastseason,qfa_net_invest_inc_lastseason,qfa_net_cash_flows_inv_act_lastseason,下个月平均收益,252日超额收益标准差,30/120日回报方差
0,20200131,-7.835821,-32.777054,12.892688,6.275304,0.195998,0.823939,0.031839,573317369519.103149,2966193000000.0,...,6153000000.0,-49711000000,734309000000.0,366000000.0,15508000000.0,3701000000.0,-21679000000.0,-6.882591,0.000075,
1,20200131,-12.54902,-53.752389,-35.345955,,0.667798,0.792767,-0.129478,2717058844.74,3579876520.95,...,110146.13,-141681708.93,931470950.48,19804979.84,-27368024.4,522089.64,426580.1,-9.41704,0.000173,
2,20200131,-7.305936,-53.390434,8.36095,3.284072,0.830685,0.647172,-0.477914,6957216000.0,7946898714.31,...,31617614.13,-189506154.15,2038584261.3,588701.23,167697580.14,58143775.39,-119567693.0,-8.538588,0.000098,
3,20200131,-10.536044,-65.538644,5.064477,16.322314,0.244554,0.771915,-0.263712,39668756537.1856,200647187000.0,...,383701000.0,-2717590000,44635485000.0,106939000.0,1949192000.0,255309000.0,-1233009000.0,-8.367769,0.000135,
4,20200131,-6.609195,-18.3783,14.002833,,1.642311,1.417896,-0.607578,22080418652.5,14041598393.98,...,-21821698.73,-791186196.31,3414537638.75,1831329.28,383315665.0,-4553726.81,-966720029.69,-12.615385,0.000122,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15641,20220131,-11.109832,16823.52667,,,,,,20846700000.0,,...,,,228247551.98,418600.0,331191245.13,1245628.82,-130739754.36,,0.000286,
15642,20220131,-4.74645,364.173743,,,,,,38573158466.959999,,...,,,5191755532.46,4077401.54,523003799.56,134118844.57,-277299585.4,,0.000251,
15643,20220131,-3.126277,53.395805,,,,,,115972892816.199997,,...,,,10095882356.51,2163568.84,1181360178.03,678336985.93,-135658787.9,,0.000325,
15644,20220131,-3.994394,8438.293288,,,,,,19830203297.959999,,...,,,3103208626.17,11481273.6,217472149.77,151668530.46,-39878737.74,,0.000203,
15645,20220131,-9.213615,-81.04766,,,,,,296838912928.73999,,...,,,6901425756.86,1487588.5,1529500911.43,65935176.24,-288798713.58,,0.000197,

In [19]:
import numpy as np

In [20]:
test = test.replace(r'^\s*$', np.NaN, regex=True)

In [21]:
test.iloc[:, 2:200].astype(float)

,date,risk_maxdownside2,avgreturny,pe_ttm,dividendyield,ps_ttm,pb_lf,peg,ev3,oper_rev,...,qfa_net_invest_inc_thiss,qfa_net_cash_flows_inv_act_thiss,qfa_oper_rev_lastseason,qfa_non_oper_rev_lastseason,qfa_net_profit_is_lastseason,qfa_net_invest_inc_lastseason,qfa_net_cash_flows_inv_act_lastseason,下个月平均收益,252日超额收益标准差,30/120日回报方差
0,20200131.0,-7.835821,-32.777054,12.892688,6.275304,0.195998,0.823939,0.031839,5.733174e+11,2.966193e+12,...,6.153000e+09,-4.971100e+10,7.343090e+11,3.660000e+08,1.550800e+10,3.701000e+09,-2.167900e+10,-6.882591,0.000075,NaN
1,20200131.0,-12.549020,-53.752389,-35.345955,NaN,0.667798,0.792767,-0.129478,2.717059e+09,3.579877e+09,...,1.101461e+05,-1.416817e+08,9.314710e+08,1.980498e+07,-2.736802e+07,5.220896e+05,4.265801e+05,-9.417040,0.000173,NaN
2,20200131.0,-7.305936,-53.390434,8.360950,3.284072,0.830685,0.647172,-0.477914,6.957216e+09,7.946899e+09,...,3.161761e+07,-1.895062e+08,2.038584e+09,5.887012e+05,1.676976e+08,5.814378e+07,-1.195677e+08,-8.538588,0.000098,NaN
3,20200131.0,-10.536044,-65.538644,5.064477,16.322314,0.244554,0.771915,-0.263712,3.966876e+10,2.006472e+11,...,3.837010e+08,-2.717590e+09,4.463548e+10,1.069390e+08,1.949192e+09,2.553090e+08,-1.233009e+09,-8.367769,0.000135,NaN
4,20200131.0,-6.609195,-18.378300,14.002833,NaN,1.642311,1.417896,-0.607578,2.208042e+10,1.404160e+10,...,-2.182170e+07,-7.911862e+08,3.414538e+09,1.831329e+06,3.833157e+08,-4.553727e+06,-9.667200e+08,-12.615385,0.000122,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15641,20220131.0,-11.109832,16823.526670,NaN,NaN,NaN,NaN,NaN,2.084670e+10,NaN,...,NaN,NaN,2.282476e+08,4.186000e+05,3.311912e+08,1.245629e+06,-1.307398e+08,NaN,0.000286,NaN
15642,20220131.0,-4.746450,364.173743,NaN,NaN,NaN,NaN,NaN,3.857316e+10,NaN,...,NaN,NaN,5.191756e+09,4.077402e+06,5.230038e+08,1.341188e+08,-2.772996e+08,NaN,0.000251,NaN
15643,20220131.0,-3.126277,53.395805,NaN,NaN,NaN,NaN,NaN,1.159729e+11,NaN,...,NaN,NaN,1.009588e+10,2.163569e+06,1.181360e+09,6.783370e+08,-1.356588e+08,NaN,0.000325,NaN
15644,20220131.0,-3.994394,8438.293288,NaN,NaN,NaN,NaN,NaN,1.983020e+10,NaN,...,NaN,NaN,3.103209e+09,1.148127e+07,2.174721e+08,1.516685e+08,-3.987874e+07,NaN,0.000203,NaN
15645,20220131.0,-9.213615,-81.047660,NaN,NaN,NaN,NaN,NaN,2.968389e+11,NaN,...,NaN,NaN,6.901426e+09,1.487588e+06,1.529501e+09,6.593518e+07,-2.887987e+08,NaN,0.000197,NaN